baseURL = "https://genkistation.github.io/photography/"
languageCode = "fr-fr"
title = "photography"
theme = []

[markup.goldmark.renderer]
unsafe = true # Autorise un peu de HTML si besoin

[server]
# Utile si un jour vous testez en local, mais pas obligatoire ici
